---
title: "Trip Matching - Part1"
author: "Dave Hurst"
date: "Thursday, January 8, 2014"
output: pdf_document
---
```{r init}
source("telematic_util.R")
data.dir <- "c:/NO_BACKUP/kaggle/telematics/drivers"
drivers.dir <- dir(data.dir)
```
## Manual Trip Matching

I've come to know driver 2591 fairly well, and was wondering if I could recognize his trip segments.  I used the following code to scan through his trips 4 at a time:

```
par(mfrow=c(2,2))
i=-3
driver.id=2591
...  (repeat this lines)
i=i+4;for (j in 1:4) {print(i+j-1); plotTrip(getTrip(driver.id,i+j-1),header=F)}
```

Here are the segments I identified as being similar (? marks less confidence):
10,11,16,37,40,43, 44,45, 47? ,49,53,54, 63?, 70,80?, 82, 104, 105?, 107, 111, 115, 117?, 123,130,131, 138, 140, 142?, 146, 154, 155, 157,162, 178,180?, 184?, 192, 198,200

Here are the plots:

```{r}
driver.id=2591
same.route <- c(10,11,16,37,40,43, 44,45, 47 ,49,53,54, 63, 70,80, 82, 104, 105, 107, 111, 115, 117, 123,130,131, 138, 140, 142, 146, 154, 155, 157,162, 178,180, 184, 192, 198,200)

for (trip.id in same.route) {
    cat("driver", driver.id, "trip", trip.id)
    plotTrip(getTrip(driver.id, trip.id))
}
```
Next step ... can we parameterize the routes to find these segments automagically?
