---
title: "Trip Sequencing Part 5"
author: "Dave Hurst"
date: "Monday, February 22, 2015"
output: html_document
---

In the previous parts, I've described how I've deconstructed the trips into segments
- A list of segments with details (or reference to details) on each segment
- A sequence of segment ID's that comprise the trip
- A of set data for each segment type  [I still haven't done this yet]

I'm going to try to reconstruct each trip out of segments made up of the following types:  

- stops *DONE: See part 1* (no driver profile for these, but we need them to describe the segment)  
- sharp turns  *DONE: See part 2*
- curves (differentiated from sharp turns by radii (as a function of speed))  *DONE: See part 3*
- straights *DONE: See part 4*
- uncategorized:  
-- short straights (too short to collect profile info)  
-- slow rolling sections (drive thrus, driveways, etc. -- no profile info)  
-- windy sections (ideally break these up later)  
-- other?  

So now let's see how all the trips compare by segment breakdown

```{r init, fig.width=10}
library(knitr)
library(reshape)
source("telematic_util.R")

data.dir <- "c:/NO_BACKUP/kaggle/telematics/drivers"

drivers.dir <- dir(data.dir)
set.seed(2349)

driver.id <- 2591

segment.summary <- function ( segs , trip ) {
    segs$tlen <- segs$tn - segs$t0 + 1
    unk.segs <- is.na( segs$type)
    segs[unk.segs, "type"] <- "uncategorized"
    stats <- data.frame(table(segs$type))
    tlen.sum <- aggregate( segs$tlen, list(segs$type), sum )
    stats <- cbind( stats, tlen.sum$x, round(tlen.sum$x/nrow(trip)*100, 2))
    colnames(stats) <- c("Type", "count", "total_t", "pct_of_trip")
    loss <- nrow(trip) - sum( stats[,"total_t"])  
    stats <- rbind(stats, data.frame(Type="loss", count=NA, total_t= loss, pct_of_trip= round(100*loss/nrow(trip), 2 )))
    stats
}

# for (trip.id in 1:200) {
#     
#     trip <- getTrip( driver.id, trip.id, v.thresh=2 )
#     
#     trip.seg <- segment.by.stops(trip)
#     trip.seg <- segment.by.turns( trip, trip.seg)
#     trip.seg <- segment.by.curve.gen( trip, trip.seg, r.thresh=300, t.thresh=4, ctype="curve")
#     trip.seg <- segment.by.curve.gen( trip, trip.seg, t.thresh=3, zone=4, ctype="straight")
#     
#     segs <- trip.seg[!grepl("^x", trip.seg$type), ]
#     segs <- segs[ order(segs$t0),]
# 
#     stats <- segment.summary( segs, trip)
#     stats$driver <- driver.id
#     stats$trip <- trip.id
#     if (exists("driver_stats")) { 
#         driver_stats <- rbind(driver_stats, stats)
#     } else {
#         driver_stats <- stats
#     }
#     print(stats)
# }
# 
# save(seg.summary, file="driver_2591_driver_stats.RData")
load(file="driver_2591_driver_stats.RData")
seg.summary <- cast( driver_stats,  trip~Type, value="count" )
seg.summary[, -ncol(seg.summary)]


```

